Repository nextsimhub/domain_decomp, pull requests merged in 2024-11, with the labels that each got.

#66 tests: recombine tests and add them to runner
  .github/workflows/actions.yml
  CMakeLists.txt
  test/CMakeLists.txt
  test/test_grid_0.cpp
  test/test_grid_0_MPI1.cpp
  test/test_grid_0_MPI2.cpp
  test/test_grid_1.cpp
  test/test_grid_1_MPI1.cpp
  test/test_grid_1_MPI2.cpp
  test/test_grid_2.cpp
  test/test_grid_2_MPI1.cpp
  test/test_grid_2_MPI2.cpp
  test/test_zoltan_partitioner_0.cpp
  test/test_zoltan_partitioner_0_MPI1.cpp
  test/test_zoltan_partitioner_0_MPI2.cpp
  test/test_zoltan_partitioner_1.cpp
  test/test_zoltan_partitioner_1_MPI1.cpp
  test/test_zoltan_partitioner_1_MPI2.cpp
  test/test_zoltan_partitioner_2.cpp
  test/test_zoltan_partitioner_2_MPI1.cpp
  test/test_zoltan_partitioner_2_MPI2.cpp
  test/test_zoltan_partitioner_2_MPI3.cpp
  test/test_zoltan_partitioner_2_MPI4.cpp
Labels: enhancement, ICCS

#62 Overhaul testing
  .github/workflows/actions.yml
  CMakeLists.txt
  README.md
  lib/doctest/LICENSE.txt
  lib/doctest/doctest.h
  lib/doctest/extensions/doctest_mpi.h
  lib/doctest/extensions/doctest_util.h
  lib/doctest/extensions/mpi_reporter.h
  lib/doctest/extensions/mpi_sub_comm.h
  test/CMakeLists.txt
  test/MainMPI.cpp
  test/main.cpp
  test/test_grid_0.cpp
  test/test_grid_1.cpp
  test/test_grid_2.cpp
  test/test_zoltan_partitioner_0.cpp
  test/test_zoltan_partitioner_1.cpp
  test/test_zoltan_partitioner_2.cpp
Labels: enhancement

#71 Fix Mac CI
  .github/workflows/actions.yml
Labels: bug, ICCS
