Repository nextsimhub/domain_decomp, pull requests merged in 2024-08, with the labels that each got.

#31 Update catch2 and fix Mac CI
  .github/workflows/actions.yml
  README.md
  test/main.cpp
  test/test_grid_0.cpp
  test/test_grid_1.cpp
  test/test_grid_2.cpp
  test/test_zoltan_partitioner_0.cpp
  test/test_zoltan_partitioner_1.cpp
  test/test_zoltan_partitioner_2.cpp
Labels: bug, enhancement

#33 Change naming scheme
  Partitioner.cpp
  Partitioner.hpp
  README.md
Labels: enhancement

#28 docs: add ascii diagram of domain decomp
  Partitioner.cpp
  Partitioner.hpp
  README.md
Labels: documentation

#40 feat: remove block option from command line args
  main.cpp
Labels: enhancement

#36 Set up clang formatting
  .clang-format
  .github/workflows/actions.yml
  Grid.cpp
  Grid.hpp
  Partitioner.cpp
  Partitioner.hpp
  Utils.hpp
  ZoltanPartitioner.cpp
  ZoltanPartitioner.hpp
  examples/zoltan_comm.cpp
  main.cpp
  test/main.cpp
  test/test_grid_0.cpp
  test/test_grid_1.cpp
  test/test_grid_2.cpp
  test/test_zoltan_partitioner_0.cpp
  test/test_zoltan_partitioner_1.cpp
  test/test_zoltan_partitioner_2.cpp
Labels: documentation

#42 Replace NetCDF files with CDL files
  .gitignore
  grids/rect3030.res.cdl
  grids/rect3030.res.nc
  results/partition_mask_2.nc
  results/partition_mask_4.nc
  results/partition_metadata_2.nc
  results/partition_metadata_4.nc
  test/CMakeLists.txt
  test/test_0.cdl
  test/test_0.nc
  test/test_1.cdl
  test/test_1.nc
  test/test_2.cdl
  test/test_2.nc
Labels: enhancement
